apiVersion: influxdata.com/v2alpha1
kind: CheckThreshold
metadata:
    name: goofy-turing-47e000
spec:
    every: 5s
    name: TempOverHeat
    query: |-
        from(bucket: "mission")
          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
          |> filter(fn: (r) => r["_measurement"] == "TempC")
          |> filter(fn: (r) => r["_field"] == "TempC")
          |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
          |> yield(name: "mean")
    status: active
    statusMessageTemplate: 'Check: ${ r._check_name } is: ${ r._level }'
    thresholds:
      - level: CRIT
        type: greater
        value: -6.6