apiVersion: influxdata.com/v2alpha1
kind: CheckThreshold
metadata:
    name: boring-pike-9f5001
spec:
    every: 5s
    name: Temps Test
    query: |-
        from(bucket: "mission")
          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
          |> filter(fn: (r) => r["_measurement"] == "temps")
          |> filter(fn: (r) => r["_field"] == "celsius")
          |> aggregateWindow(every: 1m, fn: last, createEmpty: false)
          |> yield(name: "last")
    status: active
    statusMessageTemplate: 'Check: ${ r._check_name } is: ${ r._level }'
    thresholds:
      - level: CRIT
        type: greater
        value: 70