global:
  resolve_timeout: 0s

route:
  group_wait: 0s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'webhook-receiver'

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://mission_api:8080/alert'